name: Update Spotify Playlists

on:
  schedule:
    # Run every Monday at 12:00 AM UTC (cron format: minute hour day month dayofweek)
    - cron: '0 0 * * 1'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  update-playlists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
        echo "SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}" >> .env
        echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> .env
        echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> .env
        
    - name: Run playlist update script
      run: python update_group_playlists.py
      
    - name: Upload logs (if failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playlist-update-logs
        path: |
          *.log
          .env
        retention-days: 7